default: &default
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV["DATABASE_URL"] { 5 } %>
  spoke:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV["SPOKE_DATABASE_URL"] { 5 } %>
    migrations_paths: db/spoke_migrate

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
