default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: 'postgres://localhost/identity_spoke_test_host'

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
